obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[ 0.6,  0.4], [-0.4,  0.4], [-0.4, -0.4], [ 0.6, -0.4]]
footprint_padding: 0.03
#robot_radius: ir_of_robot
inflation_radius: 0.55
transform_tolerance: 1

controller_patience: 2.0

NavfnROS:
    allow_unknown: true

observation_sources: laser_scan_sensor #point_cloud_sensor
# point_cloud_sensor: {
#     sensor_frame: camera_link,
#     data_type: PointCloud,
#     topic: /camera/depth/points,
#     expected_update_rate: 0.5,
#     marking: true,
#     clearing: true
#   }

laser_scan_sensor: { sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}


recovery_behaviors: [
    {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
]

conservative_clear:
    reset_distance: 3.00
aggressive_clear:
    reset_distance: 1.84
